-- MySQL Script generated by MySQL Workbench
-- Mon May 16 16:58:03 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oms_syn_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oms_syn_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oms_syn_db` DEFAULT CHARACTER SET utf8 ;
USE `oms_syn_db` ;

-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_region` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(45) NULL COMMENT '地区编码',
  `parent_id` INT NULL DEFAULT 0 COMMENT '父亲ID',
  `region_name` VARCHAR(45) NULL COMMENT '地区名称',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
COMMENT = '城市地区表';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_market_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_market_info` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_market_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `market_number` VARCHAR(45) NULL COMMENT '商场编号',
  `market_name` VARCHAR(45) NULL COMMENT '商场名称',
  `first_org_id` INT NULL COMMENT '大区ID',
  `second_org_id` INT NULL COMMENT '小区ID',
  `first_org_name` VARCHAR(45) NULL COMMENT '大区名称',
  `second_org_name` VARCHAR(45) NULL COMMENT '小区名称',
  `province_id` INT NULL COMMENT '省份',
  `city_id` INT NULL COMMENT '城市',
  `district_id` INT NULL COMMENT '区县',
  `market_address` VARCHAR(120) NULL COMMENT '详细地址',
  `lon` VARCHAR(10) NULL COMMENT '经度',
  `lat` VARCHAR(10) NULL COMMENT '纬度',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '商场表';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_shop_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_shop_info` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_shop_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_number` VARCHAR(45) NULL COMMENT '店铺Number',
  `market_id` INT NULL COMMENT '商场ID',
  `market_name` VARCHAR(45) NULL COMMENT '所属商场名称',
  `booth_code` VARCHAR(45) NULL COMMENT '展位编号',
  `shop_level` VARCHAR(45) NULL COMMENT '展位等级',
  `oms_shop_infocol` VARCHAR(45) NULL,
  `really_area` VARCHAR(45) NULL COMMENT '实测面积',
  `vector_area` VARCHAR(45) NULL COMMENT '图纸面积',
  `share_ratio` VARCHAR(45) NULL COMMENT '公摊系数',
  `budgetary_price` VARCHAR(45) NULL,
  `doorplate_remarks` VARCHAR(45) NULL COMMENT '门牌号',
  `booth_desc` VARCHAR(120) NULL COMMENT '展位描述',
  `company_id` VARCHAR(45) NULL COMMENT '工厂品牌公司ID',
  `dealer_id` INT NULL COMMENT '经销商ID',
  `brand_id` INT NULL COMMENT '品牌ID',
  `brand_name` VARCHAR(45) NULL COMMENT '品牌名称',
  `series_id` INT NULL COMMENT '系列ID',
  `series_name` VARCHAR(45) NULL COMMENT '系列名称',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `market_id_idx` (`market_id` ASC))
ENGINE = InnoDB
COMMENT = '展位店铺';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_company` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_number` VARCHAR(45) NULL COMMENT '品牌工厂编号',
  `company_name` VARCHAR(120) NULL,
  `province_id` INT NULL COMMENT '所在省份',
  `city_id` INT NULL COMMENT '所在城市',
  `company_address` VARCHAR(45) NULL COMMENT '厂家地址',
  `post_code` VARCHAR(45) NULL COMMENT '邮编',
  `corporation` VARCHAR(45) NULL COMMENT '董事长',
  `corporation_tel` VARCHAR(45) NULL COMMENT '董事长电话',
  `manager` VARCHAR(45) NULL COMMENT '总经理',
  `manager_tel` VARCHAR(45) NULL COMMENT '总经理电话',
  `contract` VARCHAR(45) NULL COMMENT '联系人',
  `contract_tel` VARCHAR(45) NULL COMMENT '联系人电话',
  `web_url` VARCHAR(120) NULL COMMENT '公司网址',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '品牌公司';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_brand_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_brand_info` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_brand_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NULL DEFAULT 0 COMMENT '公司ID',
  `brand_number` VARCHAR(45) NULL COMMENT '品牌编号',
  `brand_name` VARCHAR(45) NULL COMMENT '品牌名称',
  `brand_py` VARCHAR(45) NULL COMMENT '品牌拼音',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `company_id_idx` (`company_id` ASC))
ENGINE = InnoDB
COMMENT = '品牌表';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_brand_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_brand_series` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_brand_series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NULL COMMENT '品牌ID',
  `series_number` VARCHAR(45) NULL COMMENT '系列编号',
  `series_name` VARCHAR(45) NULL COMMENT '系列名称',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC))
ENGINE = InnoDB
COMMENT = '品牌系列表';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_dealer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_dealer` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_dealer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dealer_number` VARCHAR(45) NULL COMMENT '经销商编码',
  `dealer_type` INT NULL COMMENT '经销商类型',
  `person_dealer_name` VARCHAR(45) NULL COMMENT '姓名',
  `person_dealer_tel` VARCHAR(45) NULL COMMENT '电话',
  `person_dealer_idnum` VARCHAR(45) NULL COMMENT '身份证',
  `person_contact_add` VARCHAR(45) NULL COMMENT '联系地址',
  `company_name` VARCHAR(45) NULL COMMENT '公司名称',
  `province_id` INT NULL COMMENT '省份',
  `city_id` INT NULL COMMENT '城市',
  `address` VARCHAR(120) NULL COMMENT '具体地址',
  `post_code` VARCHAR(45) NULL,
  `org_cretification_no` VARCHAR(45) NULL,
  `legal_rep_tel` VARCHAR(45) NULL COMMENT '法人电话',
  `legal_repid_num` VARCHAR(45) NULL,
  `tele_phone` VARCHAR(45) NULL COMMENT '公司电话',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '经销商';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_contract` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_number` VARCHAR(45) NULL COMMENT '合同编码',
  `contract_code` VARCHAR(45) NULL COMMENT '合同编号',
  `dealer_id` INT NULL,
  `contract_startDate` VARCHAR(45) NULL,
  `contract_endDate` VARCHAR(45) NULL COMMENT '合同结束时间',
  `contract_type_id` INT NULL COMMENT '合同类型',
  `sap_contract_code` VARCHAR(45) NULL COMMENT 'SAP合同号',
  `contract_status_code` INT NULL COMMENT '合同状态',
  `remark` VARCHAR(120) NULL COMMENT '备注',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `dealer_id_idx` (`dealer_id` ASC))
ENGINE = InnoDB
COMMENT = '入住合同';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_contract_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_contract_shop` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_contract_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop_id` INT NULL COMMENT '展位id',
  `contract_id` INT NULL COMMENT '合同id',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `shop_id_idx` (`shop_id` ASC))
ENGINE = InnoDB
COMMENT = '合同店铺表';


-- -----------------------------------------------------
-- Table `oms_syn_db`.`oms_contract_brand_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oms_syn_db`.`oms_contract_brand_series` ;

CREATE TABLE IF NOT EXISTS `oms_syn_db`.`oms_contract_brand_series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_id` INT NULL COMMENT '合同ID',
  `brand_id` INT NULL COMMENT '品牌ID',
  `brand_series_id` INT NULL COMMENT '系列ID',
  `is_del` INT NULL DEFAULT 0,
  `create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `contract_id_idx` (`contract_id` ASC),
  INDEX `brand_id_idx` (`brand_id` ASC),
  INDEX `brand_series_id_idx` (`brand_series_id` ASC))
ENGINE = InnoDB
COMMENT = '合同代理的品牌及系列';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
